### ISSUE TITLE
Speech to Text Python program

### ISSUE THREAD

**Issue by reddymahendra52** [openmindsclub/H4ckT0b3rF3st-2k20#4]
* I can create a simple speech to text python program and can create a markdown to explain it so
* The markdown will contain photos  for better understanding
* And I can also create a Jupyter notebook for the same with the required code to implement the steps instructed in markdown

**Comment by reddymahendra52** [comment]
Can you please assign me this ??

**Comment by cr105ph1nx** [comment]
Awesome, please make sure to include in your README how others can contribute to your project. Push your python program in "projects/vault-of-scripts" directory and the Jupyter notebook in "projects/" directory to keep things organized!
